name: test_ansiedad
description: Un chatbot para medir ansiedad con Flutter

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0" # Asegúrate de que esto sea compatible con tu versión de Flutter

dependencies:
  
  flutter:
    sdk: flutter
  provider: ^6.1.2
  http: ^0.13.6 # Ejemplo de dependencia para solicitudes HTTP
  flutter_dotenv: ^5.0.2
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  


flutter:
  uses-material-design: true
  assets:
    - assets/chatbot_icon.png
  
